
- name: download prometheus node exporter binary locally
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz
    dest: /tmp/node_exporter-1.3.1.linux-amd64.tar.gz

- name: Add the user 'node-exporter'
  ansible.builtin.user:
    name: node-exporter
    shell: /bin/false

- name: unarchive binary tarball
  unarchive:
    src: "/tmp/node_exporter-1.3.1.linux-amd64.tar.gz"
    dest: "/tmp/"
    remote_src: yes


- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: /tmp/node_exporter-1.3.1.linux-amd64/node_exporter
    dest: /usr/local/bin/
    owner: node-exporter
    group: node-exporter
    remote_src: yes
    mode: '0755'


- name: create systemd service unit
  template:
    src: prometheus-node-exporter.service.j2
    dest: /etc/systemd/system/node-exporter.service
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'RedHat'

- name: create systemd service unit
  template:
    src: prometheus-node-exporter.service.j2
    dest: /lib/systemd/system/node-exporter.service
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'

- name: ensure prometheus node exporter service is enabled and started
  service:
    name: node-exporter
    state: restarted
    enabled: yes