---
# tasks file for php

- name: Install php extensions
  apt:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
    - php7.4
    - php7.4-mysql
    - php7.4-fpm

- name: Disable default pool
  ignore_errors: yes
  command: mv /etc/php/7.4/fpm/pool.d/www.conf /etc/php/7.4/fpm/pool.d/www.disabled creates=/etc/php-fpm.d/www.disabled
  notify: restart php-fpm

- name: Copy php-fpm configuration
  template: src=wordpress.conf dest=/etc/php/7.4/fpm/pool.d/
  notify: restart php7.4-fpm
