---
- name: Install tar
  ansible.builtin.package:
    name: tar
    state: present

- name: Download and unpack latest WordPress
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: "/srv/"
    remote_src: yes
    creates: "/srv/wordpress"

- name: Install wp-cli
  get_url: url=https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
           dest=/usr/local/bin/wp
           mode=0755

- name: Add group "wordpress"
  group: name=wordpress gid=1010

- name: Add user "wordpress"
  user: name=wordpress group=wordpress home=/srv/wordpress/ uid=1010

- name: Fetch random salts for WordPress config
  local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
  register: "wp_salt"
  become: no


- name: Copy WordPress config file
  template: src=wp-config.php dest=/srv/wordpress/

- name: Change ownership of WordPress installation
  file: path=/srv/wordpress/ owner=wordpress group=wordpress state=directory recurse=yes mode=0755

- name: Ensure files have 644 permissions
  command: chdir=/srv find . -type f -exec chmod -R 0644 {} \;

- name: Restart service php
  ansible.builtin.systemd:
    state: restarted
    name: php-fpm

