      - name: Download zabbix repo package
        get_url:
            url: "https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-1%2Bubuntu14.04_all.deb"
            dest: /tmp/zabbix.deb

      - name: Install zabbix repo
        become: yes
        apt:
            deb: /tmp/zabbix.deb
            state: present

      - name: Install zabbix agent
        become: yes
        apt:
            name: zabbix-agent
            state: present
            update_cache: yes

      - name: Copy agent configuration
        template: src=zabbix_agentd.conf dest=/etc/zabbix/zabbix_agentd.conf


      - name: enable service zabbix-agent and ensure it is not masked
        systemd:
          name: zabbix-agent
          enabled: yes
          masked: no
        become: yes