---
- name: restart php-fpm
  service: name=mariadb state=restarted
  when: ansible_os_family == 'RedHat'

- name: restart php7.4-fpm
  service: name=mysql state=restarted
  when: ansible_os_family == 'Debian'